// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6nu1ipcqE8ttey9XouV7SF7bCyCSvexY',
    appId: '1:373559806797:web:4691a4b55eca46cc388504',
    messagingSenderId: '373559806797',
    projectId: 'inventory-app-rajeev-inclass15',
    authDomain: 'inventory-app-rajeev-inclass15.firebaseapp.com',
    storageBucket: 'inventory-app-rajeev-inclass15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAie4TflBqEHLA676DRx8UQFBw7kTAR_3U',
    appId: '1:373559806797:android:27ce0077b2e475ca388504',
    messagingSenderId: '373559806797',
    projectId: 'inventory-app-rajeev-inclass15',
    storageBucket: 'inventory-app-rajeev-inclass15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1-r5zJJ9OdUp6VDce1NzjCQokuRYzvg',
    appId: '1:373559806797:ios:888758715cce674e388504',
    messagingSenderId: '373559806797',
    projectId: 'inventory-app-rajeev-inclass15',
    storageBucket: 'inventory-app-rajeev-inclass15.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1-r5zJJ9OdUp6VDce1NzjCQokuRYzvg',
    appId: '1:373559806797:ios:888758715cce674e388504',
    messagingSenderId: '373559806797',
    projectId: 'inventory-app-rajeev-inclass15',
    storageBucket: 'inventory-app-rajeev-inclass15.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6nu1ipcqE8ttey9XouV7SF7bCyCSvexY',
    appId: '1:373559806797:web:e64d7c8d94507b45388504',
    messagingSenderId: '373559806797',
    projectId: 'inventory-app-rajeev-inclass15',
    authDomain: 'inventory-app-rajeev-inclass15.firebaseapp.com',
    storageBucket: 'inventory-app-rajeev-inclass15.firebasestorage.app',
  );
}